export const BP_DEVICE_KANG = 'CARING_NURSE'
export const BP_DEVICE_MANNUAL = 'CARING_MANNUAL'
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
export const SET_CONSTANTS = 'SET_CONSTANTS'
export const SET_CONSTANTS_GROUP = 'SET_CONSTANTS_GROUP'
export const SET_REGIONS = 'SET_REGIONS'

//User
export const X_MG_AUTH_TOKEN = 'X-MG-AUTH-TOKEN'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_USERS = 'SET_USERS'
export const SET_USER_FILTER = 'SET_USER_FILTER'
export const RESET_USER_FILTER = 'RESET_USER_FILTER'
export const SET_MEMBERS_OF_USER = 'SET_MEMBERS_OF_USER'
export const SET_USER_PAGE = 'SET_USER_PAGE'

//Member
export const SET_CURRENT_MEMBER = 'SET_CURRENT_MEMBER'
export const SET_MEMBERS = 'SET_MEMBERS'
export const SET_MEMBER_FILTER = 'SET_MEMBER_FILTER'
export const RESET_MEMBER_FILTER = 'RESET_MEMBER_FILTER'
export const SET_MEMBER_PAGE = 'SET_MEMBER_PAGE'

//Role
export const SET_CURRENT_ROLE = 'SET_CURRENT_ROLE'
export const SET_ROLES = 'SET_ROLES'
export const SET_ROLE_FILTER = 'SET_ROLE_FILTER'
export const RESET_ROLE_FILTER = 'RESET_ROLE_FILTER'
export const SET_MEMBERS_OF_ROLE = 'SET_MEMBERS_OF_ROLE'
export const SET_ROLE_PAGE = 'SET_ROLE_PAGE'



// Goods
export const SET_GOODS = 'SET_GOODS'
export const SET_GOODS_FILTER = 'SET_GOODS_FILTER'
export const RESET_GOODS_FILTER = 'RESET_GOODS_FILTER'
export const SET_CURRENT_GOODS = 'SET_CURRENT_GOODS'
export const SET_GOODS_PAGE = 'SET_GOODS_PAGE'
export const SET_CURRENT_GOODS_ID = 'SET_CURRENT_GOODS_ID'

// ShoppingCart
export const SET_SHOPPING_CARTS = 'SET_SHOPPING_CARTS'
export const SET_CURRENT_SHOPPING_CART = 'SET_CURRENT_SHOPPING_CART'
export const SET_SHOPPING_CART_FILTER = 'SET_SHOPPING_CART_FILTER'
export const RESET_SHOPPING_CART_FILTER = 'RESET_SHOPPING_CART_FILTER'
export const SET_SHOPPING_CART_PAGE = 'SET_SHOPPING_CART_PAGE'

// Order
export const SET_ORDERS = 'SET_ORDERS'
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER'
export const SET_ORDER_FILTER = 'SET_ORDER_FILTER'
export const RESET_ORDER_FILTER = 'RESET_ORDER_FILTER'
export const SET_ORDER_PAGE = 'SET_ORDER_PAGE'
export const SET_CURRENT_COMMENT = 'SET_CURRENT_COMMENT'

// Message
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_MESSAGE_FILTER = 'SET_MESSAGE_FILTER'
export const RESET_MESSAGE_FILTER = 'RESET_MESSAGE_FILTER'
export const SET_CURRENT_MESSAGE = 'SET_CURRENT_MESSAGE'
export const SET_MESSAGE_PAGE = 'SET_MESSAGE_PAGE'
export const SET_CURRENT_MESSAGE_ID = 'SET_CURRENT_MESSAGE_ID'
export const PATH_MESSAGE = 'groupmessage'
export const PATH_GROUP_MESSAGE = 'group_message'
export const PATH_ADD_MESSAGE = 'add_message'
export const PATH_REMOVE_MESSAGE = 'remove_message'


